spring:
  application:
    name: gateway
server:
  port: 8000
zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    multiplicacion:
      path: /multiplicacion/**
      #url: http://localhost:8080/multiplicacion
      serviceId: multiplicacion
      #strip-prefix: false
    suma:
      path: /suma/**
      url: http://localhost:8081/suma
      #serviceId: suma
      #strip-prefix: false
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
endpoints:
  trace:
    sensitive: false
